name: Keep GitHub Contributions Active

on:
  schedule:
    - cron: "15 7 * * *"
    - cron: "35 12 * * *"
    - cron: "50 18 * * *"

  workflow_dispatch:

permissions:
  contents: write


jobs:
  daily-commit:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Configure Git
        run: |
          git config user.name "Alpha2k19"
          git config user.email "alphonseasumani8@gmail.com"

      - name: Update activity
        run: |
          echo "Last update: $(date -u)" > activity.txt


      - name: Commit changes
        run: |
          git add activity.txt
          git commit -m "chore: update activity $(date -u)" || exit 0


      - name: Push
        run: |
          git push